Added prize section. Please review.
TCP-Tech/codeutsava-frontend pull request #19
Opened 2023-01-05 18:36 UTC by Olshia

2023-01-07 19:53 UTC, sahil9001 commented
Resolve conflicts

2023-01-11 05:36 UTC, sahil9001 requested changes

2023-01-11 05:36 UTC, sahil9001 commented on src/sections/section9/Section9.js
> +                <div className="codeutsava_section9-title2">Win excitinng prizes worth upto 8 lakhs</div>
rename excitinng to exciting

2023-01-11 07:00 UTC, sahil9001 commented
Pull the latest changes

2023-01-12 03:52 UTC, sahil9001 commented
Umm I think you merged the wrong branch, please pull the `dev` branch instead of `main`.

2023-01-12 20:21 UTC, sahil9001 commented
@Olshia Merge `dev` branch changes

2023-01-14 17:04 UTC, Olshia commented on src/sections/section9/Section9.js
> +                <div className="codeutsava_section9-title2">Win excitinng prizes worth upto 8 lakhs</div>
Done

2023-01-15 12:34 UTC, merged