#5 Created Events Section
TCP-Tech/codeutsava-frontend pull request #7
Opened 2022-12-25 10:51 UTC by Kraniket901

Added file5.png in src/assets/images
Created section 3 folder containing Section3.js and Section3.css
Added Section3 Component in Homepage.js
Added href=#events in Navbar Component

2022-12-25 15:22 UTC, sahil9001 requested changes
Few points to be noted:
- Add more events so we can see the scrolling functionality of the event bar.
- Card should not have a drop shadow on hover, instead it should be elevated towards user.
- Please check the card font, it is not matching, even the margin and card spacing is improper. The developed website should not differ much from the figma design.

2022-12-25 15:23 UTC, sahil9001 commented
Only HCs have the right to review the tasks, hierarchy should be maintained. You don't have to add @virajchandra51 for review

2022-12-25 16:08 UTC, Kraniket901 commented
- Functionality Added
- Changed Card Hover Effect
- Changed Margin and Padding

2022-12-25 16:17 UTC, sahil9001 commented
![Capture](https://user-images.githubusercontent.com/32628578/209475139-1a87c484-658c-43ae-be92-bb89314aff79.PNG)
Fix this height, either make it truncated for longer texts like "Hello this is an event...." or else extend height to match the levels.

2022-12-25 16:52 UTC, Kraniket901 commented
- Fixed Line Height

2022-12-25 17:44 UTC, sahil9001 requested changes

2022-12-25 17:44 UTC, sahil9001 commented on src/components/eventCard/EventCard.css
> +    min-height: 56px;
Use `3rem` here pixels aren't relative to different sizes

2022-12-25 17:49 UTC, sahil9001 requested changes

2022-12-25 17:49 UTC, sahil9001 commented on src/components/eventCard/EventCard.css
> +    font-weight:bolder;
Set font-weight to 600 , please look at figma design. You can click on the text in design then go to the inspect tab on top right and use the css provided for reference

2022-12-25 17:49 UTC, sahil9001 commented on src/components/eventCard/EventCard.css
> +}
Add `line-height` as 24px

2022-12-25 17:49 UTC, sahil9001 commented on src/components/eventCard/EventCard.css
> +    gap: 3rem;
Set gap to `2rem`

2022-12-25 17:56 UTC, Kraniket901 commented
Done Sir

2022-12-26 06:16 UTC, sahil9001 commented
Great work, @Kraniket901 !

2022-12-26 06:17 UTC, sahil9001 approved these changes

2022-12-26 06:17 UTC, merged